###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "items": [
    {
      "bookId": 4,
      "quantity": 30
    },
    {
      "bookId": 3,
      "quantity": 30
    }
  ],
  "recipient": {
    "name": "Jan Kowalski",
    "phone": "503710835",
    "street": "Sample Street 1",
    "city": "Sample City",
    "zipCode": "00-000",
    "email": "sample@sample.com"
  }
}

###
GET http://localhost:8080/orders

###
GET http://localhost:8080/orders/9

###
PUT http://localhost:8080/orders/9/status
Content-Type: application/json

{
  "orderStatus": "SHIPPED"
}

###
