version: '3.1'

services:
  db:
    container_name: sample-bookshop-db
    image: postgres:12.4
    restart: always
    environment:
      POSTGRES_DB: bookshop
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - 7432:5432
